version: "3.7"

services:
  proxy:
    image: caddy:2.6.1-alpine
    hostname: proxy
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  influxdb:
    image: influxdb:2.4-alpine
    hostname: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env

  mqtt:
    image: eclipse-mosquitto:2
    hostname: mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-storage:/mosquitto/data/
    ports:
      - "1883:1883"

  telegraf:
    image: telegraf:1.24
    hostname: telegraf
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mqtt
    links:
      - influxdb
      - mqtt
    ports:
      - "127.0.0.1:8125:8125/udp"
    env_file:
      - .env

  kapacitor:
    image: kapacitor:1.6
    hostname: kapacitor
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_REPORTING_ENABLED=false
      - KAPACITOR_LOGGING_LEVEL=${KAPACITOR_LOGGING_LEVEL}
      - KAPACITOR_INFLUXDB_0_URLS_0=${INFLUXDB_URL}
      - KAPACITOR_INFLUXDB_0_TOKEN=${INFLUXDB_TOKEN}
      - KAPACITOR_INFLUXDB_0_KAPACITOR_HOSTNAME=kapacitor
      - TZ=${KAPACITOR_TZ}
    ports:
      - "127.0.0.1:9092:9092"
    volumes:
      - ./kapacitor/etc/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - kapacitor-storage:/var/lib/kapacitor
    depends_on:
      - influxdb

  chronograf:
    image: chronograf:1.9
    #NOTE TO SELF: 1.10.0 is broken: use at least 1.10.1 (or 1.9)
    hostname: chronograf
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
      - kapacitor
    links:
      - influxdb
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORGANIZATION}
      - KAPACITOR_URL=${KAPACITOR_URL}
      - BASE_PATH=${CHRONOGRAF_BASE_PATH}

  grafana:
    image: grafana/grafana-oss:9.3.1
    hostname: grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - "127.0.0.1:3000:3000"
    secrets:
      - grafana_password
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
      - GF_SERVER_ROOT_URL=/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORGANIZATION=${INFLUXDB_ORGANIZATION}

secrets:
   grafana_password:
     file: ./grafana/admin_password.txt

volumes:
  influxdb-storage:
    name: influxdb-storage
    external: true
  chronograf-storage:
    name: chronograf-storage
    external: true
  kapacitor-storage:
    name: kapacitor-storage
    external: true
  mosquitto-storage:
    name: mosquitto-storage
    external: true
  grafana-storage:
    name: grafana-storage
    external: true
